# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzU4ZDMwMDQ4ZTA0ZTQ1NmQ2YTMxZTJjMzdiZmZjNDMxNjkxMThhMTMyODAzZjA2MjBlOWFmYTUzYzNkNjFlNDg1MzcyZTA1NDllMDU5MDk3N2YxZjA0ZmNjNTcxZTMyMmZlZTY0ZTcyOTRiOTQxZGYxYTNjYjM3OWEzNDBmNTQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
